version: "3"

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.23.0.0/24

services:
  # Postgres with pgvector extension
  db:
    image: ankane/pgvector
    container_name: jobscraper_db
    networks:
      static-network:
        ipv4_address: 172.23.0.2
    volumes:
      - postgres_database_jobscraper_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "6321:5432"

  queue:
    image: rabbitmq:3.12.6
    container_name: jobscraper_queue
    networks:
      static-network:
        ipv4_address: 172.23.0.9
    ports:
      - "5610:5672"

  # nodejs app
  nodejs_server:
    image: jobscraper
    container_name: jobscraper_app
    networks:
      static-network:
        ipv4_address: 172.23.0.3
    build:
      args:
        EXEC_ENV: ${EXEC_ENV}
      dockerfile: Dockerfile
    volumes:
      - node_app_data:/app/
    depends_on:
      - db
      - queue
    ports:
      - "8810:8890"

  # Connection Process first time: https://stackoverflow.com/a/56617524/8714371
  # Comment out if already have DB GUI installed
  # Optional
  # ***************************************************************************
  pgadmin:
    image: dpage/pgadmin4:7
    container_name: jobscraper_pg_admin
    environment:
      - "PGADMIN_DEFAULT_EMAIL=postgres@gmail.com"
      - "PGADMIN_DEFAULT_PASSWORD=password"
    ports:
      - "6320:80"
    volumes:
      - pgadmin_config:/var/lib/pgadmin/data
    depends_on:
      - db
  # ***************************************************************************

volumes:
  node_app_data:
  postgres_database_jobscraper_data:
  pgadmin_config:
