version: "3"
services:
  # Postgres with pgvector extension
  db:
    image: ankane/pgvector
    volumes:
      - postgres_database_jobscraper_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "6321:5432"

  # Connection Process first time: https://stackoverflow.com/a/56617524/8714371
  # Comment out if already have DB GUI installed
  # Optional
  # ***************************************************************************
  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      - "PGADMIN_DEFAULT_EMAIL=default@gmail.com"
      - "PGADMIN_DEFAULT_PASSWORD=password"
    ports:
      - "6320:80"
    volumes:
      - pgadmin_config:/var/lib/pgadmin/data
    depends_on:
      - db
  # ***************************************************************************

  # # Svelte app
  app:
    image: jobscraper
    container_name: jobscraper_app
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    depends_on:
      - db

volumes:
  postgres_database_jobscraper_data:
  pgadmin_config:
